# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=/usr/lib/jvm/java-25-openjdk
org.gradle.configuration-cache=false
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=26.1
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
# Mod Properties
mod_version=1.0.4
maven_group=com.imeesa
archives_base_name=togglesneakhotkey
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.145.1+26.1